#!/bin/bash

source secrets

export HUBOT_BASE="/home/hubot/hubot"
export PATH="$HUBOT_BASE/node_modules/.bin:$HUBOT_BASE/node_modules/hubot/node_modules/.bin:$PATH"

export HUBOT_NAME=scrotbot
export HUBOT_LOG_LEVEL=1

echo $PATH

./bin/hubot --adapter slack
